# Dependabot will run on day 15 of each month at 01:42 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      day: 19
      timezone: "Europe/Berlin"
      cronjob: "42 1 15 * *"
    open-pull-requests-limit: 15
    assignees:
      - "patricknitsch"
    versioning-strategy: "increase"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      day: 19
      timezone: "Europe/Berlin"
      cronjob: "42 1 15 * *"
    open-pull-requests-limit: 15
    assignees:
      - "patricknitsch"
