version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: monthly
      day: "monday"
      time: "00:05"
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
    assignees:
      - "patricknitsch"
    versioning-strategy: "increase"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
      day: "monday"
      time: "00:05"
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
    assignees:
      - "patricknitsch"
